const SOURCES=[
{name:'LEGO.com U.S.',use:'Official MSRP, availability, sale pricing and Retiring Soon / Last Chance status'},
{name:'Brick Domain',use:'Live retirement dates and recent date-change tracking'},
{name:'Brick Fanatics',use:'Theme-by-theme 2026 retirement snapshots and monthly changes'},
{name:'Brickset',use:'Set metadata, release/exit records, ratings, ownership and wanted counts'},
{name:'BrickEconomy',use:'Secondary-market context and post-retirement projections; not used as an official retirement authority'},
{name:'Toys N Bricks',use:'U.S. Last Chance / retiring-soon snapshots and sale observations'},
{name:'Master the Bricks',use:'Independent retirement roster cross-check'},
{name:'Brick Scouts',use:'Independent retirement list and change cross-check'},
{name:'Team Bricks',use:'Independent retirement timing cross-check'},
{name:'Brick Ranker',use:'Market/popularity context and set comparisons'},
{name:'Brick Sleuth',use:'Retailer-specific U.S. price-history cross-checks'},
{name:'Amazon U.S.',use:'Current retail pricing only when sold by Amazon.com and shipped by Amazon'},
{name:'Walmart U.S.',use:'Current retail pricing only when sold and shipped by Walmart.com'},
{name:'Target',use:'Current U.S. retailer pricing and promotions'},
{name:'Best Buy',use:'Current U.S. retailer pricing and clearance'},
{name:'Barnes & Noble',use:'Current U.S. retailer pricing and LEGO promotions'},
{name:'Macy’s / GameStop / Costco / Sam’s Club',use:'Additional legitimate U.S. retailer checks where applicable'}
];
const DATE_LABELS={'2026-04-30':'April 30, 2026 — Retired','2026-07-31':'July 31, 2026 — Retired','2026-08-31':'August 31, 2026 — Next / Urgent','2026-12-31':'December 31, 2026 — Current tracker'};
let DATA=[];const $=s=>document.querySelector(s);const app=$('#app');const search=$('#search'),dateFilter=$('#dateFilter'),themeFilter=$('#themeFilter'),priorityFilter=$('#priorityFilter');
function saleVerified(x){return x.current&&/\$/.test(x.current)&&!/Full price/i.test(x.current)}
function urgent(x){return x.risk==='RETIRED'||x.risk==='EXTREME'||x.risk==='HIGH'}
function callClass(x){const c=(x.call||'').toLowerCase();if(/buy now|priority|buy near|buy at|buy ≤/.test(c)||x.risk==='EXTREME')return'urgent';if(/watch|good|buy around|buy on/.test(c))return'watch';return''}
function imgFallback(img){img.style.display='none';img.nextElementSibling.style.display='block'}
window.imgFallback=imgFallback;
function card(x){const best=x.current==='Not verified today'?'No verified current winner yet':x.current;const sold=saleVerified(x);return `<article class="card"><div class="picture"><img loading="lazy" src="${x.image}" alt="LEGO ${x.setno} ${escapeHtml(x.name)}" onerror="imgFallback(this)"><div class="img-fail">Image temporarily unavailable<br><b>${x.setno}</b></div></div><div class="body"><div class="name">${x.setno} — ${escapeHtml(x.name)}</div><div class="meta">${escapeHtml(x.theme)}${x.pieces?` • ${x.pieces.toLocaleString()} pieces`:''}</div><div class="row"><b>🗓 Retirement</b><span>${x.date}</span></div><div class="row"><b>💰 MSRP</b><span>${escapeHtml(x.msrp||'Not verified')}</span></div><div class="pricebox ${sold?'verified-sale':''}"><div class="best">🏷️ BEST PRICE TODAY: ${escapeHtml(best)}</div><div class="meta">Only the cheapest verified retailer is shown. Amazon/Walmart marketplace sellers are excluded.</div></div><div class="row"><b>📉 Historical low</b><span>${escapeHtml(x.lowest||'Not verified')}</span></div><div class="row"><b>⭐ Popularity</b><span>${escapeHtml(x.popularity||'—')}</span></div><div class="row"><b>📈 Appreciation</b><span>${escapeHtml(x.potential||'—')}</span></div><div class="row"><b>🔥 Retirement risk</b><span>${escapeHtml(x.risk||'—')}</span></div><div class="row"><b>🎯 Target price</b><span>${escapeHtml(x.target||'—')}</span></div><div class="sourcebadge">Retirement date: cross-referenced tracker</div><div class="call ${callClass(x)}">🚦 ${escapeHtml(x.call||'WATCH')}</div></div></article>`}
function escapeHtml(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function render(){const q=search.value.trim().toLowerCase(),d=dateFilter.value,t=themeFilter.value,p=priorityFilter.value;let rows=DATA.filter(x=>(!q||`${x.setno} ${x.name}`.toLowerCase().includes(q))&&(!d||x.date===d)&&(!t||x.theme===t)&&(!p||(p==='urgent'&&urgent(x))||(p==='high'&&['VERY HIGH','HIGH'].includes(x.popularity))||(p==='sale'&&saleVerified(x))));$('#resultsMeta').textContent=`Showing ${rows.length.toLocaleString()} of ${DATA.length.toLocaleString()} sets`;if(!rows.length){app.innerHTML='<div class="empty">No sets match those filters.</div>';return}let html='';for(const date of [...new Set(rows.map(x=>x.date))].sort()){const dr=rows.filter(x=>x.date===date);html+=`<section class="date-section"><div class="date-head"><h2>${DATE_LABELS[date]||date}</h2><span>${dr.length} sets</span></div>`;for(const theme of [...new Set(dr.map(x=>x.theme))].sort()){const tr=dr.filter(x=>x.theme===theme);html+=`<section class="theme-section"><div class="theme-head"><h3>${escapeHtml(theme)}</h3><span>${tr.length} sets</span></div><div class="grid">${tr.map(card).join('')}</div></section>`}html+='</section>'}app.innerHTML=html}
function setup(){const dates=[...new Set(DATA.map(x=>x.date))].sort(),themes=[...new Set(DATA.map(x=>x.theme))].sort();dateFilter.innerHTML+=$dates(dates);themeFilter.innerHTML+=themes.map(t=>`<option value="${escapeHtml(t)}">${escapeHtml(t)}</option>`).join('');$('#setCount').textContent=DATA.length.toLocaleString();$('#sourceCount').textContent=SOURCES.length;$('#urgentCount').textContent=DATA.filter(urgent).length.toLocaleString();['input','change'].forEach(ev=>search.addEventListener(ev,render));[dateFilter,themeFilter,priorityFilter].forEach(el=>el.addEventListener('change',render));$('#clear').onclick=()=>{search.value='';dateFilter.value='';themeFilter.value='';priorityFilter.value='';render()};const dlg=$('#sourcesDialog');$('#sourceBtn').onclick=()=>dlg.showModal();$('#closeSources').onclick=()=>dlg.close();$('#sourcesList').innerHTML=`<div class="source-list">${SOURCES.map(s=>`<div class="source-item"><b>${escapeHtml(s.name)}</b><span>${escapeHtml(s.use)}</span></div>`).join('')}</div>`;render()}
function $dates(ds){return ds.map(d=>`<option value="${d}">${DATE_LABELS[d]||d}</option>`).join('')}
(async()=>{try{const raw=Uint8Array.from(atob(window.DATA_GZIP_B64||''),c=>c.charCodeAt(0));const ds=new DecompressionStream('gzip');const txt=await new Response(new Blob([raw]).stream().pipeThrough(ds)).text();DATA=JSON.parse(txt);setup()}catch(e){app.innerHTML=`<div class="empty"><b>Could not load tracker data.</b><br>${escapeHtml(e.message)}</div>`}})();