window.PRICE_CHANGES=[
 {setno:'43267',name:'Princess Castle & Royal Pets',retailer:'Target',type:'drop',oldPrice:97.99,newPrice:96.99,oldPct:25,newPct:25,when:'Aug. 26, 2026 • 2:06 AM PT',newSale:false,newLow:false,retailerChanged:false,note:'Target dropped back by $1.00 to $96.99, matching the tracker’s existing verified historical low from Aug. 25. LEGO is $129.99 and available now; Target remains the cheapest directly verified qualifying retailer. Brickset continues to show a Dec. 31, 2026 exit.'},
 {setno:'43267',name:'Princess Castle & Royal Pets',retailer:'Target',type:'rise',oldPrice:96.99,newPrice:97.99,oldPct:25,newPct:25,when:'Aug. 26, 2026 • 1:00 AM PT',newSale:false,newLow:false,retailerChanged:false,note:'Target increased by $1.00 from the previous verified $96.99 winner. The $96.99 price remains the stored historical low. LEGO and Best Buy are $129.99 and Barnes & Noble is also $129.99; Target remains the cheapest directly verified qualifying retailer. Brickset and Brick Fanatics continue to support Dec. 31, 2026 retirement.'},
 {setno:'43270',name:"Moana's Adventure Canoe",retailer:'Target',type:'drop',oldPrice:43.49,newPrice:38.49,oldPct:28,newPct:36,when:'Aug. 26, 2026 • 12:18 AM PT',newSale:false,newLow:false,retailerChanged:false,note:'Target returned to $38.49, restoring the earlier 36% discount and matching the previously verified historical low. Target shows Add to cart. Brick Domain continues to list Dec. 2026 retirement.'},
 {setno:'43260',name:"Moana's Island Fun",retailer:'Target',type:'drop',oldPrice:15.95,newPrice:14.99,oldPct:20,newPct:25,when:'Aug. 26, 2026 • 12:18 AM PT',newSale:false,newLow:false,retailerChanged:true,note:'Target is again the verified winner at $14.99, down from the stored $15.95 Walmart winner. The price matches the previously verified historical low. Target shows In Stock and Add to cart. Brick Domain and Brickset continue to list Dec. 2026 retirement.'},
 {setno:'21279',name:'The Enderman Tower',retailer:'Target',type:'drop',oldPrice:95.99,newPrice:79.99,oldPct:4,newPct:20,when:'Aug. 25, 2026 • 7:57 PM PT',newSale:false,newLow:false,retailerChanged:false,note:'Target dropped back from $95.99 to $79.99, restoring the earlier 20% discount and matching the previously verified historical low. Target shows Add to cart; Walmart is higher and LEGO/Best Buy are also higher where directly listed. Brick Fanatics continues to list Dec. 31, 2026 retirement.'},
 {setno:'21282',name:'The Parrot Houses',retailer:'Target',type:'drop',oldPrice:69.99,newPrice:48.99,oldPct:0,newPct:30,when:'Aug. 25, 2026 • 7:06 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target shows $48.99 in stock; LEGO lists $69.99. Brick Fanatics includes the set in the current Dec. 31, 2026 Minecraft retirement roster.'},
 {setno:'21266',name:'The Nether Lava Battle',retailer:'Target',type:'drop',oldPrice:9.99,newPrice:7.19,oldPct:0,newPct:28,when:'Aug. 25, 2026 • 7:06 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target shows $7.19 and Add to cart; LEGO is $9.99. Brick Fanatics lists the set for Dec. 31, 2026 retirement.'},
 {setno:'21269',name:'The Armadillo Mine Expedition',retailer:'Target',type:'drop',oldPrice:29.99,newPrice:23.99,oldPct:0,newPct:20,when:'Aug. 25, 2026 • 7:06 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target shows $23.99 in stock; LEGO and Best Buy list $29.99. Brick Fanatics lists the set for Dec. 31, 2026 retirement.'},
 {setno:'21270',name:'The Mooshroom House',retailer:'Target',type:'drop',oldPrice:49.99,newPrice:45.49,oldPct:0,newPct:9,when:'Aug. 25, 2026 • 7:06 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target shows $45.49 in stock; LEGO lists $49.99. Brick Fanatics lists the set for Dec. 31, 2026 retirement.'},
 {setno:'21278',name:'The Pillager Outpost and Ravager',retailer:'Target',type:'drop',oldPrice:79.99,newPrice:73.99,oldPct:0,newPct:8,when:'Aug. 25, 2026 • 7:06 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target shows $73.99 in stock; LEGO lists $79.99. Brick Fanatics lists the set for Dec. 31, 2026 retirement.'},
 {setno:'21279',name:'The Enderman Tower',retailer:'Target',type:'rise',oldPrice:79.99,newPrice:95.99,oldPct:20,newPct:4,when:'Aug. 25, 2026 • 7:06 PM PT',newSale:false,newLow:false,retailerChanged:false,note:'Target price increased from the previously stored $79.99 winner to $95.99. The prior $79.99 remains the verified historical low. LEGO and Best Buy are $99.99, so Target remains the cheapest verified qualifying retailer. Brick Fanatics lists Dec. 31, 2026 retirement.'},
 {setno:'21272',name:'Woodland Mansion Fighting Ring',retailer:'Target',type:'drop',oldPrice:49.99,newPrice:27.99,oldPct:0,newPct:44,when:'Aug. 25, 2026 • 6:07 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target shows $27.99; Best Buy direct is higher. Brick Fanatics lists the set in the 2026 Minecraft retirement roster.'},
 {setno:'21268',name:'The Baby Pig House',retailer:'Target',type:'drop',oldPrice:19.99,newPrice:12.79,oldPct:0,newPct:36,when:'Aug. 25, 2026 • 6:07 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target shows $12.79 in stock; Best Buy is $19.99. Brick Fanatics lists the set in the 2026 Minecraft retirement roster.'},
 {setno:'21274',name:'The Warden Encounter',retailer:'Target',type:'drop',oldPrice:19.99,newPrice:13.99,oldPct:0,newPct:30,when:'Aug. 25, 2026 • 6:07 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target shows $13.99 in stock; Best Buy direct is $19.99. Brick Fanatics lists the set in the 2026 Minecraft retirement roster.'},
 {setno:'21275',name:'The TNT Jungle House',retailer:'Target',type:'drop',oldPrice:29.99,newPrice:23.99,oldPct:0,newPct:20,when:'Aug. 25, 2026 • 6:07 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target shows $23.99 while LEGO is $29.99. Brick Fanatics lists the set in the 2026 Minecraft retirement roster.'},
 {setno:'42642',name:'Friendship Movie Night',retailer:'LEGO',type:'drop',oldPrice:14.99,newPrice:11.99,oldPct:0,newPct:20,when:'Aug. 25, 2026 • 3:14 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. LEGO is $11.99 on backorder; Target currently shows $14.99. Brickset records a July 31, 2026 exit and LEGO marks the set Retiring Soon.'},
 {setno:'77054',name:"Leif's Caravan & Garden Shop",retailer:'Target',type:'drop',oldPrice:29.99,newPrice:23.99,oldPct:0,newPct:20,when:'Aug. 25, 2026 • 3:14 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale/winner layer. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. Target is $23.99 and in stock; LEGO ties at $23.99 but is backordered. Brickset records a July 31, 2026 exit and LEGO marks the set Retiring Soon.'},
 {setno:'71494',name:"Zoey's Time Owl",retailer:'LEGO',type:'drop',oldPrice:29.99,newPrice:20.99,oldPct:0,newPct:30,when:'Aug. 25, 2026 • 3:14 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. LEGO is $20.99 and available now; Target shows $24.99. Brickset records a July 31, 2026 exit.'},
 {setno:'71495',name:'Mateo vs. Cyber Brain Mech',retailer:'LEGO',type:'drop',oldPrice:34.99,newPrice:27.99,oldPct:0,newPct:20,when:'Aug. 25, 2026 • 2:02 PM PT',newSale:true,newLow:false,retailerChanged:true,note:'New verified sale and retailer winner. Previous tracker winner was not verified, so MSRP is used as the comparison baseline. LEGO shows the set at 20% off on backorder; Target is out of stock at $34.99 and Best Buy is $34.99. Brick Fanatics continues to list a July 31, 2026 retirement target.'},
 {setno:'76470',name:'Enchanted Flying Ford Anglia',retailer:'Target',type:'drop',oldPrice:67.99,newPrice:65.99,oldPct:15,newPct:18,when:'Aug. 25, 2026 • 12:13 PM PT',newSale:false,newLow:false,retailerChanged:false,note:'Target price dropped $2.00 and returned to the previously verified historical low of $65.99. Brickset and Brick Fanatics continue to show a Dec. 31, 2026 retirement target.'},
 {setno:'21273',name:'The Ghast Balloon Village Attack',retailer:'Target',type:'drop',oldPrice:55.99,newPrice:44.79,oldPct:20,newPct:36,when:'Aug. 25, 2026 • 11:02 AM PT',newSale:false,newLow:false,retailerChanged:false,note:'Target sale deepened from 20% to 36% off and returned to the previously verified historical low of $44.79.'},
 {setno:'43267',name:'Princess Castle & Royal Pets',retailer:'Target',type:'drop',oldPrice:97.99,newPrice:96.99,oldPct:25,newPct:25,when:'Aug. 25, 2026 • 10:04 AM PT',newSale:false,newLow:true,retailerChanged:false,note:'Verified Target price dropped another $1.00 and set a new stored low. Discount remains 25% when measured against the $129.99 U.S. RRP.'},
 {setno:'76785',name:"Thing's Apartment",retailer:'LEGO',type:'drop',oldPrice:89.99,newPrice:53.99,oldPct:0,newPct:40,when:'Aug. 25, 2026 • 7:14 AM PT',newSale:false,newLow:false,retailerChanged:true,note:'New verified retailer winner. Previous tracker winner was not verified; comparison baseline is MSRP. LEGO marks the set Retiring Soon and available now.'},
 {setno:'21271',name:'The Trial Chamber',retailer:'LEGO',type:'drop',oldPrice:39.99,newPrice:23.99,oldPct:0,newPct:40,when:'Aug. 25, 2026 • 7:14 AM PT',newSale:false,newLow:false,retailerChanged:true,note:'New verified retailer winner. Previous tracker winner was not verified; comparison baseline is MSRP. LEGO marks the set Retiring Soon; currently backordered.'},
 {setno:'76448',name:"Fawkes: Dumbledore's Phoenix",retailer:'LEGO',type:'drop',oldPrice:22.99,newPrice:16.09,oldPct:0,newPct:30,when:'Aug. 25, 2026 • 7:14 AM PT',newSale:false,newLow:false,retailerChanged:true,note:'New verified retailer winner. Previous tracker winner was not verified; comparison baseline is MSRP. LEGO marks the set Retiring Soon and available now.'},
 {setno:'71439',name:'Adventures with Interactive LEGO Mario',retailer:'LEGO',type:'drop',oldPrice:49.99,newPrice:34.99,oldPct:0,newPct:30,when:'Aug. 25, 2026 • 7:14 AM PT',newSale:false,newLow:false,retailerChanged:true,note:'New verified retailer winner. Previous tracker winner was not verified; comparison baseline is MSRP. LEGO marks the set Retiring Soon; currently backordered.'},
 {setno:'10440',name:'Balancing & Stacking Tree',retailer:'LEGO',type:'drop',oldPrice:19.99,newPrice:13.99,oldPct:0,newPct:30,when:'Aug. 25, 2026 • 7:14 AM PT',newSale:false,newLow:false,retailerChanged:true,note:'New verified retailer winner. Previous tracker winner was not verified; comparison baseline is MSRP. LEGO marks the set Retiring Soon; currently backordered.'},
 {setno:'77055',name:'Able Sisters Clothing Shop',retailer:'LEGO',type:'drop',oldPrice:39.99,newPrice:27.99,oldPct:0,newPct:30,when:'Aug. 25, 2026 • 7:14 AM PT',newSale:false,newLow:false,retailerChanged:true,note:'New verified retailer winner. Previous tracker winner was not verified; comparison baseline is MSRP. LEGO marks the set Retiring Soon and available now.'},
 {setno:'43270',name:"Moana's Adventure Canoe",retailer:'Target',type:'drop',oldPrice:43.49,newPrice:38.49,oldPct:28,newPct:36,when:'Aug. 25, 2026 • 7:05 AM PT',newSale:false,newLow:true,retailerChanged:false,note:'New verified low; discount deepened by 8 percentage points.'},
 {setno:'43260',name:"Moana's Island Fun",retailer:'Target',type:'drop',oldPrice:19.99,newPrice:14.99,oldPct:0,newPct:25,when:'Aug. 25, 2026 • 7:05 AM PT',newSale:true,newLow:true,retailerChanged:false,note:'New sale detected; current price matches the verified historical low.'},
 {setno:'21273',name:'The Ghast Balloon Village Attack',retailer:'Target',type:'rise',oldPrice:44.79,newPrice:55.99,oldPct:36,newPct:20,when:'Aug. 24, 2026',newSale:false,newLow:false,retailerChanged:false,note:'Discount became smaller; prior verified low remains $44.79.'},
 {setno:'76470',name:'Enchanted Flying Ford Anglia',retailer:'Target',type:'rise',oldPrice:65.99,newPrice:67.99,oldPct:18,newPct:15,when:'Aug. 24, 2026',newSale:false,newLow:false,retailerChanged:false,note:'Price increased from the previous verified low.'}
];
(function(){
 const rows=(window.PRICE_CHANGES||[]).slice();
 const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const norm=s=>String(s||'').replace(/\./g,'').replace(/\s+/g,' ').trim();
 const today=norm(new Date().toLocaleDateString('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric',year:'numeric'}));
 const isToday=x=>norm(String(x.when||'').split('•')[0])===today;
 const whenKey=x=>{const raw=String(x.when||'').replace('•',' ').replace(/\s+PT\s*$/,'').trim();const n=Date.parse(raw);return Number.isFinite(n)?n:0};
 const todays=rows.filter(isToday);
 const drops=todays.filter(x=>x.type==='drop').length;
 const newSales=todays.filter(x=>x.newSale===true).length;
 const largest=todays.reduce((m,x)=>Math.max(m,(Number(x.newPct)||0)-(Number(x.oldPct)||0)),0);
 const latest=todays.length?todays.reduce((a,b)=>whenKey(a)>=whenKey(b)?a:b).when:'No verified change today';
 const pulse=document.getElementById('pricePulse');
 if(pulse){pulse.innerHTML=`<div class="pulse-head"><div><p class="eyebrow">TODAY’S PRICE PULSE</p><h2>Verified LEGO price changes</h2><p>Computed automatically from the stored verified change history.</p></div></div><div class="pulse-grid"><div class="pulse-stat good"><strong>${drops}</strong><span>price drops / better sales today</span></div><div class="pulse-stat good"><strong>${newSales}</strong><span>newly-on-sale sets today</span></div><div class="pulse-stat hot"><strong>+${largest} pts</strong><span>largest discount improvement today</span></div><div class="pulse-stat time"><strong>${esc(latest)}</strong><span>latest verified price check</span></div></div>`;}
 const host=document.getElementById('priceChanges'); if(!host)return;
 const rank=x=>isToday(x)?0:1;
 rows.sort((a,b)=>rank(a)-rank(b)||whenKey(b)-whenKey(a)||((b.newPct-b.oldPct)-(a.newPct-a.oldPct)));
 const label=x=>x.type==='saleended'?'✕ SALE ENDED':x.newSale&&x.retailerChanged?'★ NEW SALE • ⇄ NEW RETAILER WINNER':x.retailerChanged?'⇄ RETAILER WINNER CHANGED':x.newSale?'★ NEW SALE':x.newLow?'🏆 NEW HISTORICAL LOW':x.type==='rise'?'↑ PRICE INCREASE':'↓ PRICE DROP / DEEPER DISCOUNT';
 const cls=x=>x.type==='saleended'?'saleended':x.newSale?'newsale':x.retailerChanged?'retailer':x.newLow?'newlow':x.type==='rise'?'up':'down';
 const allDrops=rows.filter(x=>x.type==='drop').length, rises=rows.filter(x=>x.type==='rise'||x.type==='saleended').length;
 host.innerHTML=`<div class="changefeed-head"><div><p class="eyebrow dark">PRICE MOVEMENT</p><h2>Verified changes, newest first</h2></div><div class="changefeed-stats"><b>${allDrops} drops / better sales stored</b><span>${rises} increases / sale endings stored</span></div></div><div class="changefeed-grid">${rows.map(x=>{const delta=x.newPrice-x.oldPrice,pctDelta=x.newPct-x.oldPct;return `<article class="price-change ${cls(x)}"><div class="pc-top"><span>${label(x)}</span><b>${pctDelta>0?'+':''}${pctDelta} pts discount</b></div><h3>${esc(x.setno)} — ${esc(x.name)}</h3><p class="pc-price"><s>$${x.oldPrice.toFixed(2)}</s> → <strong>$${x.newPrice.toFixed(2)}</strong> at ${esc(x.retailer)}</p><p class="pc-discount">${x.oldPct}% off → <b>${x.newPct}% off</b> ${delta<0?`• save $${Math.abs(delta).toFixed(2)} more`:delta>0?`• costs $${delta.toFixed(2)} more`:''}</p><p class="pc-note">${esc(x.note)}</p><small>Verified ${esc(x.when)}</small></article>`}).join('')}</div><p class="changefeed-foot">Today's summary and this feed are both calculated from the same stored verified history. When the previous tracker winner was unverified, MSRP is used only as the comparison baseline and the note says so. Marketplace offers that fail the Amazon/Walmart seller rules are not counted.</p>`;
})();