Object.assign(window.DATA_PRICE_PATCHES,{"42649":{"current":"$24.99 — Target (17% off)","lowest":"$24.99 — Target (Aug 28, 2026)","checked":"Aug. 28, 2026 • 5:16 PM PT","stock":"Target: $24.99 sale, down from the previously verified $27.49 winner. Best Buy: $29.99 sold by Best Buy with Add to cart. Historical low $24.99 is matched, not broken."}});
window.PRICE_CHANGES.unshift({setno:'42649',name:'Heartlake City Candy Store',retailer:'Target',type:'drop',oldPrice:27.49,newPrice:24.99,oldPct:8,newPct:17,when:'Aug. 28, 2026 • 5:16 PM PT',day:'2026-08-28',minute:1036,newSale:false,newLow:false,retailerChanged:false,note:'Target has returned to $24.99, improving from the previously verified $27.49 winner and restoring about 17% off the $29.99 U.S. MSRP. This matches the tracker’s existing $24.99 historical low rather than setting a new low. Best Buy remains $29.99 sold by Best Buy. Retirement remains Dec. 31, 2026; Brick Fanatics and Brick Ranker continue to support the December 2026 window.'});
(function(){
 const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const rows=(window.PRICE_CHANGES||[]).slice().sort((a,b)=>String(b.day||'').localeCompare(String(a.day||''))||((b.minute||0)-(a.minute||0)));
 const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
 const get=t=>parts.find(p=>p.type===t)?.value||''; const pacificDay=`${get('year')}-${get('month')}-${get('day')}`;
 const today=rows.filter(x=>x.day===pacificDay),drops=today.filter(x=>x.type==='drop').length,newSales=today.filter(x=>x.newSale).length,best=today.reduce((m,x)=>Math.max(m,(x.newPct||0)-(x.oldPct||0)),0),latest=today.reduce((m,x)=>(x.minute||0)>(m.minute||-1)?x:m,{minute:-1,when:'No verified check today'});
 const pulse=document.getElementById('pricePulse'); if(pulse)pulse.innerHTML=`<div class="pulse-head"><div><p class="eyebrow dark">TODAY'S PRICE PULSE</p><h2>Verified LEGO price changes today</h2></div><span>Computed from stored verified price-change history</span></div><div class="pulse-grid"><div><strong>${drops}</strong><span>price drops / better sales</span></div><div><strong>${newSales}</strong><span>newly-on-sale sets</span></div><div><strong>+${best} pts</strong><span>largest discount improvement</span></div><div><strong>${latest.minute>=0?esc(latest.when.split('•')[1]?.trim()||latest.when):'—'}</strong><span>latest verified check</span></div></div>`;
 const host=document.getElementById('priceChanges'); if(!host)return;
 const kind=x=>x.type==='rise'?['up','↑ PRICE INCREASE']:(x.type==='saleended'||x.type==='ending')?['saleended','SALE ENDED']:(x.newSale&&x.newLow)?['newlow','NEW SALE • NEW HISTORICAL LOW']:x.newSale?['newsale','NEW SALE']:x.newLow?['newlow','NEW HISTORICAL LOW']:x.retailerChanged?['retailer','RETAILER WINNER CHANGED']:(x.newPct||0)>(x.oldPct||0)?['deeper','DEEPER DISCOUNT']:['down','↓ PRICE DROP'];
 host.innerHTML=`<div class="changefeed-head"><div><p class="eyebrow dark">PRICE MOVEMENT</p><h2>Verified changes, newest first</h2></div><div class="changefeed-stats"><b>${today.filter(x=>x.type==='drop').length} drops today</b><span>${today.filter(x=>x.type==='rise'||x.type==='saleended'||x.type==='ending').length} increases / sale endings today</span></div></div><div class="changefeed-grid">${rows.map(x=>{const [cls,label]=kind(x),delta=(x.newPct||0)-(x.oldPct||0);return `<article class="price-change ${cls}"><div class="pc-top"><span>${label}</span><b>${delta>0?'+':''}${delta} pts discount</b></div><h3>${esc(x.setno)} — ${esc(x.name)}</h3><p class="pc-price"><s>$${Number(x.oldPrice).toFixed(2)}</s> → <strong>$${Number(x.newPrice).toFixed(2)}</strong> at ${esc(x.retailer)}</p><p class="pc-discount">${x.oldPct}% off → <b>${x.newPct}% off</b></p><p class="pc-note">${esc(x.note)}</p><small>Verified ${esc(x.when)}</small></article>`}).join('')}</div><p class="changefeed-foot">Today's entries appear first. Amazon and Walmart offers are only counted when the required first-party seller and shipping conditions are verified.</p>`;
})();