(function(){
 const additions=[
  {setno:'42665',name:'Puppy Playground',retailer:'Target',type:'saleended',oldPrice:7.99,newPrice:9.89,oldPct:20,newPct:1,when:'Aug. 27, 2026 • 9:05 PM PT',day:'2026-08-27',minute:1265,newSale:false,newLow:false,retailerChanged:false,note:'The earlier $7.99 Target sale has ended. Target is now $9.89 and in stock with Add to cart, still narrowly below LEGO at $9.99. The $7.99 historical low is preserved. Current retirement tracking continues to place 42665 in the Dec. 31, 2026 Friends cohort.'},
  {setno:'42695',name:'Horse & Baby Foal Trailer',retailer:'Best Buy',type:'rise',oldPrice:19.19,newPrice:20.99,oldPct:36,newPct:30,when:'Aug. 27, 2026 • 9:05 PM PT',day:'2026-08-27',minute:1265,newSale:false,newLow:false,retailerChanged:true,note:'Target has moved up to $23.99; Best Buy is now the cheapest verified qualifying retailer at $20.99 with pickup/shipping available. The $19.19 Target historical low is preserved. Retirement remains Dec. 31, 2026 across current Friends retirement tracking.'},
  {setno:'42685',name:'Heartlake City Fashion Show',retailer:'Best Buy',type:'rise',oldPrice:31.19,newPrice:34.99,oldPct:38,newPct:30,when:'Aug. 27, 2026 • 9:05 PM PT',day:'2026-08-27',minute:1265,newSale:false,newLow:false,retailerChanged:true,note:'Target has moved up to $39.99; Best Buy is now the cheapest verified qualifying retailer at $34.99, sold by Best Buy with pickup/shipping available. The $31.19 Target historical low is preserved. Brick Fanatics and Brick Ranker continue to support a December 2026 retirement window.'},
  {setno:'42665',name:'Puppy Playground',retailer:'Target',type:'drop',oldPrice:9.99,newPrice:7.99,oldPct:0,newPct:20,when:'Aug. 27, 2026 • 8:13 PM PT',day:'2026-08-27',minute:1213,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target sale/winner at $7.99 versus the $9.99 LEGO U.S. MSRP. Target shows Add to cart; LEGO is $9.99 and available now, and Best Buy is $9.99 sold by Best Buy with pickup available. Current Brick Fanatics retirement tracking keeps 42665 in the Dec. 31, 2026 Friends cohort.'},
  {setno:'42649',name:'Heartlake City Candy Store',retailer:'Target',type:'drop',oldPrice:29.99,newPrice:27.49,oldPct:0,newPct:8,when:'Aug. 27, 2026 • 8:13 PM PT',day:'2026-08-27',minute:1213,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target winner at $27.49 versus the $29.99 LEGO U.S. MSRP. Target shows In Stock and Add to cart; LEGO is $29.99 available now and Best Buy is $29.99 sold by Best Buy. Brick Fanatics continues to place 42649 in the Dec. 31, 2026 Friends retirement cohort.'},
  {setno:'42659',name:'Friendship Road-Trip Travel Car',retailer:'Target',type:'drop',oldPrice:19.99,newPrice:19.39,oldPct:0,newPct:3,when:'Aug. 27, 2026 • 6:08 PM PT',day:'2026-08-27',minute:1088,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target sale/winner at $19.39 versus the $19.99 LEGO U.S. MSRP; Target shows the item in stock with Add to cart and LEGO remains $19.99. Brickset and Brick Fanatics continue to support Dec. 31, 2026 retirement.'},
  {setno:'42671',name:'Plant Café & Flower Shop',retailer:'Target',type:'drop',oldPrice:99.99,newPrice:76.99,oldPct:0,newPct:23,when:'Aug. 27, 2026 • 6:08 PM PT',day:'2026-08-27',minute:1088,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target sale/winner at $76.99, about 23% below the $99.99 LEGO U.S. MSRP, with the current Target listing showing Add to cart. LEGO remains $99.99. Brickset and Brick Fanatics continue to place 42671 in the Dec. 31, 2026 retirement cohort.'},
  {setno:'42661',name:'Costume Party with Unicorn & Fairy',retailer:'Target',type:'drop',oldPrice:39.99,newPrice:25.99,oldPct:0,newPct:35,when:'Aug. 27, 2026 • 4:14 PM PT',day:'2026-08-27',minute:974,newSale:true,newLow:true,retailerChanged:true,note:'Price Movement history correction for the already-stored live winner: Target is $25.99 and in stock with Add to cart versus $39.99 at Best Buy sold by Best Buy and the $39.99 LEGO U.S. MSRP. Brick Fanatics continues to place 42661 in the Dec. 31, 2026 retirement cohort.'},
  {setno:'42644',name:'Heartlake City Ice Cream Truck',retailer:'Target',type:'drop',oldPrice:19.99,newPrice:18.49,oldPct:0,newPct:8,when:'Aug. 27, 2026 • 5:03 PM PT',day:'2026-08-27',minute:1023,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target sale/winner. Target is $18.49 versus the $19.99 LEGO U.S. RRP and Best Buy regular price. Brickset and Brick Fanatics continue to place this set in the Dec. 31, 2026 retirement cohort.'},
  {setno:'42650',name:'Pet Accessories Shop',retailer:'Target',type:'drop',oldPrice:39.99,newPrice:31.99,oldPct:0,newPct:20,when:'Aug. 27, 2026 • 5:03 PM PT',day:'2026-08-27',minute:1023,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target winner at $31.99, 20% below the $39.99 LEGO U.S. RRP; Best Buy remains $39.99 sold by Best Buy. Brickset and Brick Fanatics continue to support Dec. 31, 2026 retirement.'},
  {setno:'42695',name:'Horse & Baby Foal Trailer',retailer:'Target',type:'drop',oldPrice:20.99,newPrice:19.19,oldPct:30,newPct:36,when:'Aug. 27, 2026 • 2:10 PM PT',day:'2026-08-27',minute:850,newSale:false,newLow:false,retailerChanged:true,note:'Target has returned to $19.19 with Add to cart, beating Best Buy at $20.99 and LEGO at $29.99. This matches the existing verified historical low rather than setting a new one. Retirement remains Dec. 31, 2026 in current Friends retirement tracking.'},
  {setno:'42685',name:'Heartlake City Fashion Show',retailer:'Target',type:'drop',oldPrice:34.99,newPrice:31.19,oldPct:30,newPct:38,when:'Aug. 27, 2026 • 2:10 PM PT',day:'2026-08-27',minute:850,newSale:false,newLow:false,retailerChanged:true,note:'Target has returned to $31.19 with Add to cart, beating Best Buy at $34.99 and LEGO/Macy\'s at $49.99. This matches the existing verified historical low rather than setting a new one. Retirement remains Dec. 31, 2026 in current Friends retirement tracking.'},
  {setno:'42695',name:'Horse & Baby Foal Trailer',retailer:'Best Buy',type:'rise',oldPrice:19.19,newPrice:20.99,oldPct:36,newPct:30,when:'Aug. 27, 2026 • 12:58 PM PT',day:'2026-08-27',minute:778,newSale:false,newLow:false,retailerChanged:true,note:'The deeper $19.19 Target clearance was temporarily no longer the cheapest verified purchasable offer. Target had moved to $23.99; Best Buy was $20.99, sold by Best Buy. Historical low remained $19.19.'},
  {setno:'42685',name:'Heartlake City Fashion Show',retailer:'Best Buy',type:'rise',oldPrice:31.19,newPrice:34.99,oldPct:38,newPct:30,when:'Aug. 27, 2026 • 12:58 PM PT',day:'2026-08-27',minute:778,newSale:false,newLow:false,retailerChanged:true,note:'The deeper $31.19 Target clearance was temporarily unavailable as the cheapest verified offer. Target had moved to $39.99; Best Buy was $34.99, sold by Best Buy. Historical low remained $31.19.'}
 ];
 const old=window.PRICE_CHANGES||[];
 const keys=new Set(additions.map(x=>`${x.setno}|${x.when}|${x.type}`));
 window.PRICE_CHANGES=additions.concat(old.filter(x=>!keys.has(`${x.setno}|${x.when}|${x.type}`)));
 const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const rows=window.PRICE_CHANGES.slice().sort((a,b)=>(b.day||'').localeCompare(a.day||'')||((b.minute||0)-(a.minute||0)));
 const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
 const get=t=>parts.find(p=>p.type===t)?.value||'';
 const todayKey=`${get('year')}-${get('month')}-${get('day')}`;
 const today=rows.filter(x=>x.day===todayKey);
 const drops=today.filter(x=>x.type==='drop').length;
 const newSales=today.filter(x=>x.newSale).length;
 const largest=today.reduce((m,x)=>Math.max(m,(x.newPct||0)-(x.oldPct||0)),0);
 const latest=today.slice().sort((a,b)=>(b.minute||0)-(a.minute||0))[0];
 const pulse=document.getElementById('pricePulse');
 if(pulse){pulse.innerHTML=`<div class="changefeed-head"><div><p class="eyebrow dark">TODAY'S PRICE PULSE</p><h2>Verified LEGO price movement</h2></div><div class="changefeed-stats"><b>${drops} price drops / better sales</b><span>${newSales} newly-on-sale sets</span></div></div><div class="scoregrid"><div><span>Price drops / better sales</span><b>${drops}</b></div><div><span>Newly on sale</span><b>${newSales}</b></div><div><span>Largest discount improvement</span><b>+${largest} pts</b></div><div><span>Latest verified check</span><b>${latest?esc(latest.when.replace(/^.*•\s*/,'')):'No check today'}</b></div></div>`;}
 const host=document.getElementById('priceChanges');
 if(host){
  const badge=x=>{const b=[];if(x.newSale)b.push('<span class="pill green">NEW SALE</span>');if(x.newLow)b.push('<span class="pill blue">NEW LOW</span>');if(x.type==='drop'&&!x.newSale)b.push('<span class="pill green">DEEPER / RETURNED SALE</span>');if(x.type==='rise')b.push('<span class="pill red">PRICE INCREASE</span>');if(x.type==='saleended')b.push('<span class="pill red">SALE ENDED</span>');if(x.retailerChanged)b.push('<span class="pill amber">RETAILER CHANGED</span>');return b.join(' ')};
  host.innerHTML=`<div class="changefeed-head"><div><p class="eyebrow dark">PRICE MOVEMENT</p><h2>Latest verified changes</h2></div><div class="changefeed-stats"><b>${drops} drops / better sales today</b><span>${today.filter(x=>x.type==='rise'||x.type==='saleended').length} increases / sale endings today</span></div></div><div class="changefeed-grid">${rows.slice(0,40).map(x=>{const delta=(x.newPrice||0)-(x.oldPrice||0),pd=(x.newPct||0)-(x.oldPct||0);return `<article class="price-change ${x.type==='drop'?'down':'up'}"><div class="pc-top"><span>${esc(x.day===todayKey?'TODAY':'RECENT')}</span><b>${pd>0?'+':''}${pd} pts discount</b></div><div style="display:flex;gap:5px;flex-wrap:wrap;margin-top:7px">${badge(x)}</div><h3>${esc(x.setno)} — ${esc(x.name)}</h3><p class="pc-price"><s>$${Number(x.oldPrice).toFixed(2)}</s> → <strong>$${Number(x.newPrice).toFixed(2)}</strong> at ${esc(x.retailer)}</p><p class="pc-discount">${x.oldPct}% off → <b>${x.newPct}% off</b>${delta<0?` • save $${Math.abs(delta).toFixed(2)} more`:delta>0?` • costs $${delta.toFixed(2)} more`:''}</p><p class="pc-note">${esc(x.note)}</p><small>Verified ${esc(x.when)}</small></article>`}).join('')}</div><p class="changefeed-foot">Verified U.S. retailer changes only. Amazon counts only when sold and shipped by Amazon; Walmart counts only when sold and shipped by Walmart. Third-party marketplace offers are excluded.</p>`;
 }
})();