(function(){
 const additions=[
  {setno:'42677',name:'Dog Treats Bakery',retailer:'Best Buy',type:'drop',oldPrice:17.99,newPrice:12.99,oldPct:40,newPct:57,when:'Aug. 28, 2026 • 7:04 AM PT',day:'2026-08-28',minute:424,newSale:false,newLow:true,retailerChanged:true,note:'Best Buy dropped 42677 from the prior verified $17.99 winner to $12.99 clearance, about 57% off the $29.99 U.S. MSRP. Best Buy verifies the item is sold by Best Buy with Add to cart. Target remains $17.99 in stock; LEGO is $29.99 available now; Walmart is $23.95 sold and shipped by Walmart.com. This is a 17-point deeper discount, a retailer-winner change, and a new tracker-verified historical low. Retirement remains Dec. 31, 2026 across Brickset, Brick Ranker, and the current Brick Fanatics 2026 Friends retirement roster.'},
  {setno:'42666',name:'Cat Birthday Party & Tree House',retailer:'Target',type:'drop',oldPrice:29.99,newPrice:26.49,oldPct:0,newPct:12,when:'Aug. 28, 2026 • 12:57 AM PT',day:'2026-08-28',minute:57,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target sale/winner at $26.49 versus the $29.99 LEGO U.S. MSRP. Target shows In Stock and Add to cart; LEGO is $29.99 and available now, and Best Buy is $29.99. Walmart shows $26.00, but this check did not establish that it is both sold and shipped by Walmart.com, so that offer is excluded. Brickset records a Dec. 31, 2026 exit and Brick Fanatics’ August retirement list keeps 42666 in the 2026 Friends cohort.'}
 ];
 const old=window.PRICE_CHANGES||[];
 const keys=new Set(additions.map(x=>`${x.setno}|${x.when}|${x.type}`));
 window.PRICE_CHANGES=additions.concat(old.filter(x=>!keys.has(`${x.setno}|${x.when}|${x.type}`)));
 const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
 const rows=window.PRICE_CHANGES.slice().sort((a,b)=>(b.day||'').localeCompare(a.day||'')||((b.minute||0)-(a.minute||0)));
 const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
 const get=t=>parts.find(p=>p.type===t)?.value||'';
 const todayKey=`${get('year')}-${get('month')}-${get('day')}`;
 const today=rows.filter(x=>x.day===todayKey);
 const drops=today.filter(x=>x.type==='drop').length;
 const newSales=today.filter(x=>x.newSale).length;
 const largest=today.reduce((m,x)=>Math.max(m,(x.newPct||0)-(x.oldPct||0)),0);
 const latest=today.slice().sort((a,b)=>(b.minute||0)-(a.minute||0))[0];
 const pulse=document.getElementById('pricePulse');
 if(pulse){pulse.innerHTML=`<div class="changefeed-head"><div><p class="eyebrow dark">TODAY'S PRICE PULSE</p><h2>Verified LEGO price movement</h2></div><div class="changefeed-stats"><b>${drops} price drops / better sales</b><span>${newSales} newly-on-sale sets</span></div></div><div class="scoregrid"><div><span>Price drops / better sales</span><b>${drops}</b></div><div><span>Newly on sale</span><b>${newSales}</b></div><div><span>Largest discount improvement</span><b>+${largest} pts</b></div><div><span>Latest verified check</span><b>${latest?esc(latest.when.replace(/^.*•\s*/,'')):'No check today'}</b></div></div>`;}
 const host=document.getElementById('priceChanges');
 if(host){
  const badge=x=>{const b=[];if(x.newSale)b.push('<span class="pill green">NEW SALE</span>');if(x.newLow)b.push('<span class="pill blue">NEW LOW</span>');if(x.type==='drop'&&!x.newSale)b.push('<span class="pill green">DEEPER / RETURNED SALE</span>');if(x.type==='rise')b.push('<span class="pill red">PRICE INCREASE</span>');if(x.type==='saleended')b.push('<span class="pill red">SALE ENDED</span>');if(x.retailerChanged)b.push('<span class="pill amber">RETAILER CHANGED</span>');return b.join(' ')};
  host.innerHTML=`<div class="changefeed-head"><div><p class="eyebrow dark">PRICE MOVEMENT</p><h2>Latest verified changes</h2></div><div class="changefeed-stats"><b>${drops} drops / better sales today</b><span>${today.filter(x=>x.type==='rise'||x.type==='saleended').length} increases / sale endings today</span></div></div><div class="changefeed-grid">${rows.slice(0,40).map(x=>{const delta=(x.newPrice||0)-(x.oldPrice||0),pd=(x.newPct||0)-(x.oldPct||0);return `<article class="price-change ${x.type==='drop'?'down':'up'}"><div class="pc-top"><span>${esc(x.day===todayKey?'TODAY':'RECENT')}</span><b>${pd>0?'+':''}${pd} pts discount</b></div><div style="display:flex;gap:5px;flex-wrap:wrap;margin-top:7px">${badge(x)}</div><h3>${esc(x.setno)} — ${esc(x.name)}</h3><p class="pc-price"><s>$${Number(x.oldPrice).toFixed(2)}</s> → <strong>$${Number(x.newPrice).toFixed(2)}</strong> at ${esc(x.retailer)}</p><p class="pc-discount">${x.oldPct}% off → <b>${x.newPct}% off</b>${delta<0?` • save $${Math.abs(delta).toFixed(2)} more`:delta>0?` • costs $${delta.toFixed(2)} more`:''}</p><p class="pc-note">${esc(x.note)}</p><small>Verified ${esc(x.when)}</small></article>`}).join('')}</div><p class="changefeed-foot">Verified U.S. retailer changes only. Amazon counts only when sold and shipped by Amazon; Walmart counts only when sold and shipped by Walmart. Third-party marketplace offers are excluded.</p>`;
 }
})();