window.PRICE_CHANGES=[
 {setno:'77056',name:"Blathers's Museum Collection",retailer:'Best Buy',type:'drop',oldPrice:79.99,newPrice:55.99,oldPct:0,newPct:30,when:'Aug. 27, 2026 • 9:13 AM PT',day:'2026-08-27',minute:553,newSale:true,newLow:false,retailerChanged:true,note:'Best Buy product page is again purchasable at $55.99, sold by Best Buy, with shipping available and pickup at some locations. This reverses the 8:04 AM sale-ending fallback to LEGO $79.99 and returns to the previously verified $55.99 historical low. Retirement remains Dec. 31, 2026 in Brickset and Brick Fanatics.'},
 {setno:'71052',name:'Series 29',retailer:'Best Buy',type:'drop',oldPrice:4.99,newPrice:3.49,oldPct:0,newPct:30,when:'Aug. 27, 2026 • 8:04 AM PT',day:'2026-08-27',minute:484,newSale:true,newLow:true,retailerChanged:true,note:'New verified Best Buy Top Deal at $3.49 versus $4.99 MSRP, with pickup available. This is a new tracker-verified historical low and a 30% discount. Brick Fanatics continues to place Series 29 in the Aug. 31, 2026 retirement window.'},
 {setno:'77056',name:"Blathers's Museum Collection",retailer:'LEGO',type:'saleended',oldPrice:55.99,newPrice:79.99,oldPct:30,newPct:0,when:'Aug. 27, 2026 • 8:04 AM PT',day:'2026-08-27',minute:484,newSale:false,newLow:false,retailerChanged:true,note:'The $55.99 Best Buy winner is now sold out, and Target is also out of stock at $62.99. LEGO is available now at $79.99, so the effective purchasable sale has ended. Historical low remains $55.99. Retirement remains Dec. 31, 2026.'},
 {setno:'77056',name:"Blathers's Museum Collection",retailer:'Best Buy',type:'drop',oldPrice:79.99,newPrice:55.99,oldPct:0,newPct:30,when:'Aug. 27, 2026 • 7:12 AM PT',day:'2026-08-27',minute:432,newSale:true,newLow:true,retailerChanged:true,note:'New verified Best Buy sale and retailer winner. Best Buy is sold by Best Buy at $55.99 with shipping available; Target is $62.99. Brickset records a Dec. 31, 2026 exit and Brick Fanatics keeps 77056 in the December 2026 Animal Crossing retirement group.'},
 {setno:'60463',name:'Fire Ladder Truck',retailer:'Target',type:'drop',oldPrice:18.99,newPrice:15.99,oldPct:5,newPct:20,when:'Aug. 27, 2026 • 6:03 AM PT',day:'2026-08-27',minute:363,newSale:false,newLow:false,retailerChanged:true,note:'Target returned to $15.99 and is in stock with Add to cart, restoring the 20% discount and matching the verified historical low. Retirement remains Dec. 31, 2026 across Brickset, Brick Ranker, Brickonomics and current 2026 retirement lists.'},
 {setno:'60452',name:'Donut Truck',retailer:'Target',type:'saleended',oldPrice:15.99,newPrice:19.99,oldPct:20,newPct:0,when:'Aug. 27, 2026 • 6:03 AM PT',day:'2026-08-27',minute:363,newSale:false,newLow:false,retailerChanged:true,note:'The $15.99 clearance ended at Target. Target is now $19.99 and in stock; LEGO is sold out and marked Retiring Soon. The current Walmart offer is sold by Datalogistix, so it is excluded under the first-party seller rule. Historical low remains $15.99. Brickset records a Jul. 31, 2026 exit.'},
 {setno:'71512',name:'Crocodile Submarine',retailer:'Target',type:'drop',oldPrice:69.99,newPrice:48.99,oldPct:0,newPct:30,when:'Aug. 27, 2026 • 5:09 AM PT',day:'2026-08-27',minute:309,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target sale and retailer winner. Target shows $48.99 in stock with Add to cart; LEGO is $69.99 and available now. Retirement remains Dec. 31, 2026 in Brickset and the current August retirement roster.'},
 {setno:'71513',name:'Nightmare Scorpion Digger',retailer:'Target',type:'drop',oldPrice:49.99,newPrice:34.99,oldPct:0,newPct:30,when:'Aug. 27, 2026 • 5:09 AM PT',day:'2026-08-27',minute:309,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target sale and retailer winner. Target shows $34.99 in stock with Add to cart; LEGO and Best Buy are $49.99. Retirement remains Dec. 31, 2026 in Brickset and the current August retirement roster.'},
 {setno:'71514',name:'Dino Jet',retailer:'Target',type:'drop',oldPrice:99.99,newPrice:84.99,oldPct:0,newPct:15,when:'Aug. 27, 2026 • 5:09 AM PT',day:'2026-08-27',minute:309,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target sale and retailer winner. Target shows $84.99 in stock; LEGO and Best Buy are $99.99. Retirement remains Dec. 31, 2026 across Brickset and the current August retirement roster.'},
 {setno:'71500',name:'Nightmare Shark Submarine',retailer:'Target',type:'drop',oldPrice:149.99,newPrice:134.99,oldPct:0,newPct:10,when:'Aug. 27, 2026 • 5:09 AM PT',day:'2026-08-27',minute:309,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target retailer winner at $134.99 versus LEGO at $149.99. Target shows the set available to add to cart. Retirement remains Dec. 31, 2026 in the current August retirement roster.'},
 {setno:'71492',name:"Mateo's Fire Chameleon",retailer:'Target',type:'drop',oldPrice:54.99,newPrice:32.99,oldPct:0,newPct:40,when:'Aug. 27, 2026 • 4:08 AM PT',day:'2026-08-27',minute:248,newSale:true,newLow:true,retailerChanged:true,note:'New verified Target sale and retailer winner. Target shows $32.99 in stock with Add to cart. Best Buy no longer offers the set in new condition and Amazon has no featured offer. Discount is measured against the $54.99 U.S. MSRP; retirement remains Dec. 31, 2026 across current DREAMZzz retirement trackers.'},
 {setno:'60404',name:'Burger Truck',retailer:'Target',type:'drop',oldPrice:15.99,newPrice:12.79,oldPct:20,newPct:36,when:'Aug. 27, 2026 • 3:15 AM PT',day:'2026-08-27',minute:195,newSale:false,newLow:false,retailerChanged:true,note:'Target returned to the deeper clearance price at $12.79 and is in stock with Add to cart. This matches the previously verified historical low and restores a 36% discount versus LEGO U.S. MSRP.'},
 {setno:'60452',name:'Donut Truck',retailer:'Target / Walmart',type:'drop',oldPrice:19.99,newPrice:15.99,oldPct:0,newPct:20,when:'Aug. 27, 2026 • 2:05 AM PT',day:'2026-08-27',minute:125,newSale:true,newLow:true,retailerChanged:true,note:'Earlier today Target and qualifying Walmart both showed $15.99. LEGO was sold out and marked Retiring Soon.'},
 {setno:'60463',name:'Fire Ladder Truck',retailer:'Target / Walmart',type:'rise',oldPrice:15.99,newPrice:18.99,oldPct:20,newPct:5,when:'Aug. 27, 2026 • 2:05 AM PT',day:'2026-08-27',minute:125,newSale:false,newLow:false,retailerChanged:true,note:'The deeper Target sale temporarily ended; Target and qualifying Walmart were $18.99. Historical low remained $15.99.'},
 {setno:'60404',name:'Burger Truck',retailer:'Target / Walmart',type:'rise',oldPrice:12.79,newPrice:15.99,oldPct:36,newPct:20,when:'Aug. 27, 2026 • 2:05 AM PT',day:'2026-08-27',minute:125,newSale:false,newLow:false,retailerChanged:true,note:'The deeper clearance price temporarily ended; historical verified low remained $12.79.'},
 {setno:'60471',name:'Arctic Explorer Science Lab Truck',retailer:'Target',type:'drop',oldPrice:119.99,newPrice:114.99,oldPct:0,newPct:4,when:'Aug. 27, 2026 • 1:01 AM PT',day:'2026-08-27',minute:61,newSale:true,newLow:false,retailerChanged:true,note:'New verified Target retailer winner at $114.99 and in stock. LEGO, Best Buy and Barnes & Noble were $119.99.'},
 {setno:'60337',name:'Express Passenger Train',retailer:'Target',type:'drop',oldPrice:189.99,newPrice:181.99,oldPct:0,newPct:4,when:'Aug. 27, 2026 • 1:01 AM PT',day:'2026-08-27',minute:61,newSale:true,newLow:false,retailerChanged:true,note:'New verified Target retailer winner at $181.99 and in stock versus LEGO $189.99.'},
 {setno:'60463',name:'Fire Ladder Truck',retailer:'Target',type:'drop',oldPrice:19.99,newPrice:15.99,oldPct:0,newPct:20,when:'Aug. 27, 2026 • 1:01 AM PT',day:'2026-08-27',minute:61,newSale:true,newLow:false,retailerChanged:true,note:'Target briefly showed a 20% sale at $15.99 before the price rose and later returned to $15.99.'}
];
(function(){
 const esc=v=>String(v??'').replace(/[&<>\\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;'}[c]));
 const rows=(window.PRICE_CHANGES||[]).slice().sort((a,b)=>String(b.day||'').localeCompare(String(a.day||''))||((b.minute||0)-(a.minute||0)));
 const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
 const get=t=>parts.find(p=>p.type===t)?.value||''; const pacificDay=`${get('year')}-${get('month')}-${get('day')}`;
 const today=rows.filter(x=>x.day===pacificDay);
 const drops=today.filter(x=>x.type==='drop').length;
 const newSales=today.filter(x=>x.newSale).length;
 const best=today.reduce((m,x)=>Math.max(m,(x.newPct||0)-(x.oldPct||0)),0);
 const latest=today.reduce((m,x)=>(x.minute||0)>(m.minute||-1)?x:m,{minute:-1,when:'No verified check today'});
 const pulse=document.getElementById('pricePulse');
 if(pulse){pulse.innerHTML=`<div class="pulse-head"><div><p class="eyebrow dark">TODAY'S PRICE PULSE</p><h2>Verified LEGO price changes today</h2></div><span>Computed from stored verified price-change history</span></div><div class="pulse-grid"><div><strong>${drops}</strong><span>price drops / better sales</span></div><div><strong>${newSales}</strong><span>newly-on-sale sets</span></div><div><strong>+${best} pts</strong><span>largest discount improvement</span></div><div><strong>${latest.minute>=0?esc(latest.when.split('•')[1]?.trim()||latest.when):'—'}</strong><span>latest verified check</span></div></div>`;}
 const host=document.getElementById('priceChanges'); if(!host)return;
 function kind(x){if(x.type==='rise')return['up','↑ PRICE INCREASE'];if(x.type==='saleended'||x.type==='ending')return['saleended','SALE ENDED'];if(x.newSale&&x.newLow)return['newlow','NEW SALE • NEW HISTORICAL LOW'];if(x.newSale)return['newsale','NEW SALE'];if(x.newLow)return['newlow','NEW HISTORICAL LOW'];if(x.retailerChanged)return['retailer','RETAILER WINNER CHANGED'];if((x.newPct||0)>(x.oldPct||0))return['deeper','DEEPER DISCOUNT'];return['down','↓ PRICE DROP'];}
 host.innerHTML=`<div class="changefeed-head"><div><p class="eyebrow dark">PRICE MOVEMENT</p><h2>Verified changes, newest first</h2></div><div class="changefeed-stats"><b>${today.filter(x=>x.type==='drop').length} drops today</b><span>${today.filter(x=>x.type==='rise'||x.type==='saleended'||x.type==='ending').length} increases / sale endings today</span></div></div><div class="changefeed-grid">${rows.map(x=>{const [cls,label]=kind(x),delta=(x.newPct||0)-(x.oldPct||0);return `<article class="price-change ${cls}"><div class="pc-top"><span>${label}</span><b>${delta>0?'+':''}${delta} pts discount</b></div><h3>${esc(x.setno)} — ${esc(x.name)}</h3><p class="pc-price"><s>$${Number(x.oldPrice).toFixed(2)}</s> → <strong>$${Number(x.newPrice).toFixed(2)}</strong> at ${esc(x.retailer)}</p><p class="pc-discount">${x.oldPct}% off → <b>${x.newPct}% off</b></p><p class="pc-note">${esc(x.note)}</p><small>Verified ${esc(x.when)}</small></article>`}).join('')}</div><p class="changefeed-foot">Today's entries appear first. Amazon and Walmart offers are only counted when the required first-party seller and shipping conditions are verified.</p>`;
})();